apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redispvc
    namespace: cp2
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: default
    resources:
        requests:
            storage: 1Gi