[defaults]
host_key_checking=False

[vm]
Azure-vm-saintremy ansible_host=4.223.65.242 ansible_user=azureuser ansible_ssh_private_key_file=/Users/kokomac/Documents/GitHub/actividad2/.keys/Azure-vm-saintremy_private_key.pem

[vm:vars]
ansible_python_interpreter=/usr/bin/python3

[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[aks_cluster]
ansible_host=https://saintremycasopractico2-uddt0z1l.hcp.swedencentral.azmk8s.io:443 ansible_connection=local ansible_python_interpreter=/usr/bin/python3

